version: '3'
services:

  employee:
    image: 224111447235.dkr.ecr.eu-central-1.amazonaws.com/employee-frontend_employee:latest
    hostname: employee
    environment:
      - ENVIRONMENT=production
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 10
      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '0.10'
          memory: 256M
        # Soft limit - Docker makes best effort to return to it
        reservations:
          cpus: '0.10'
          memory: 128M
      restart_policy:
        condition: any
    logging:
       driver: json-file
       options:
          max-size: "2m"
          max-file: "3"
    dns: 
      - 8.8.8.8
      - 8.8.4.4
networks:
  default:
    external:
      name: production